local comments = require("review-loop.ui.comments")
local feedback = require("review-loop.feedback")
local eq = assert.are.same

describe("comments store", function()
  it("add assigns ids and normalizes file-level comments to line = nil", function()
    local s = comments.new()
    local id1 = comments.add(s, { path = "a.ts", side = "modified", line = 10, body = "x" })
    local id2 = comments.add(s, { path = "a.ts", side = "file", line = 5, body = "note" })
    eq("c1", id1)
    eq("c2", id2)
    eq(10, s.items[id1].line)
    assert.is_nil(s.items[id2].line)
  end)

  it("update/remove mutate the store", function()
    local s = comments.new()
    local id = comments.add(s, { path = "a", side = "file", body = "x" })
    comments.update(s, id, "y")
    eq("y", comments.get(s, id).body)
    comments.remove(s, id)
    assert.is_nil(comments.get(s, id))
  end)

  it("for_path and count_for_path filter by path", function()
    local s = comments.new()
    comments.add(s, { path = "a", side = "file", body = "1" })
    comments.add(s, { path = "b", side = "file", body = "2" })
    comments.add(s, { path = "a", side = "file", body = "3" })
    eq(2, #comments.for_path(s, "a"))
    eq(2, comments.count_for_path(s, "a"))
    eq(1, comments.count_for_path(s, "b"))
  end)

  it("all returns insertion order", function()
    local s = comments.new()
    comments.add(s, { path = "b", side = "file", body = "1" })
    comments.add(s, { path = "a", side = "file", body = "2" })
    local ids = {}
    for _, c in ipairs(comments.all(s)) do ids[#ids + 1] = c.path end
    eq({ "b", "a" }, ids)
  end)

  it("to_review_comments drops blank bodies and feeds feedback.compose", function()
    local s = comments.new()
    comments.add(s, { path = "a.ts", mode = "checkpoint", side = "modified", line = 4, body = "fix" })
    comments.add(s, { path = "a.ts", side = "file", body = "  " })
    local rc = comments.to_review_comments(s)
    eq(1, #rc)
    local out = feedback.compose(rc)
    eq("Please address the following review feedback:\n\n1. a.ts:4 (current)\n   fix", out)
  end)

  it("add preserves a line range via line_end and drops it for singles/files", function()
    local s = comments.new()
    local r = comments.add(s, { path = "a", side = "modified", line = 3, line_end = 6, body = "x" })
    local single = comments.add(s, { path = "a", side = "modified", line = 9, line_end = 9, body = "y" })
    local file = comments.add(s, { path = "a", side = "file", line = 1, line_end = 2, body = "z" })
    eq(6, s.items[r].line_end)
    assert.is_nil(s.items[single].line_end)
    assert.is_nil(s.items[file].line_end)
  end)

  it("to_review_comments carries line_end into feedback", function()
    local s = comments.new()
    comments.add(s, { path = "a.ts", mode = "head", side = "original", line = 2, line_end = 4, body = "fix" })
    local out = feedback.compose(comments.to_review_comments(s))
    eq("Please address the following review feedback:\n\n1. a.ts:2-4 (HEAD)\n   fix", out)
  end)
end)
